#!/usr/bin/env bash
# Configures nginx with a custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

service nginx restart
